# Generated by Django 4.0.8 on 2022-12-23 23:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(upload_to=core.models.upload_thumbnail),
        ),
    ]
